apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
  labels:
    app: mysite
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: bodra84/mysite:v1.0.0
        ports:
        - containerPort: 80
