apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-nodeport
  namespace: myapp
spec:
  selector:
    app: mysite
  ports:
    - name: web-port
      protocol: TCP
      port: 80
      nodePort: 30500
  type: NodePort
