name: Build and deploy app
on:
  push:
      tags:
        - 'v*'
      branches:
        - 'main'
jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./myapp
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mysite:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/mysite:latest

  deploy:
    name: 'Deploy to Kubernetes'
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4     
      
      - name: Update docker image
        run: |
          sed -i "s|{{ image }}|${{ secrets.DOCKER_USERNAME }}/mysite:${{ github.sha }}|g" k8s/deployment.yml
      
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}          
        with:
          args: -n myapp apply -f k8s/